/**
 * Parameter declarations for every generator and effect. Pure data (no
 * Three.js) so the control UI, the modulation compiler and the renderers all
 * share one source of truth.
 */
import type { ModSource, ParamBag, ParamSpec } from '@shared/types/engine';

export interface ModuleDef {
  kind: string;
  label: string;
  description: string;
  params: ParamSpec[];
}

const f = (key: string, label: string, def: number, min: number, max: number, step = 0.01, hint?: string): ParamSpec => ({ key, label, type: 'float', default: def, min, max, step, hint });
const i = (key: string, label: string, def: number, min: number, max: number, hint?: string): ParamSpec => ({ key, label, type: 'int', default: def, min, max, step: 1, hint });
const e = (key: string, label: string, def: string, options: string[], hint?: string): ParamSpec => ({ key, label, type: 'enum', default: def, options, hint });
const b = (key: string, label: string, def: boolean, hint?: string): ParamSpec => ({ key, label, type: 'bool', default: def, hint });
const t = (key: string, label: string, def: string, hint?: string): ParamSpec => ({ key, label, type: 'text', default: def, hint });

export const GENERATORS: ModuleDef[] = [
  {
    kind: 'spectrumBars',
    label: 'Spectrum bars',
    description: 'Log-frequency bar EQ with peak caps, LED segments, mirroring and a reflective floor.',
    params: [
      i('bars', 'Bars', 64, 8, 256),
      f('gap', 'Gap', 0.28, 0, 0.8),
      f('height', 'Height', 0.58, 0.1, 0.95),
      f('horizon', 'Horizon', 0.3, 0.05, 0.95),
      e('mirror', 'Mirror', 'none', ['none', 'center', 'sides'], 'center: grow up and down from the horizon · sides: lows in the middle'),
      i('segments', 'LED segments', 0, 0, 48, '0 = solid bars'),
      f('roundness', 'Roundness', 1, 0, 1),
      e('colorMode', 'Colour by', 'frequency', ['frequency', 'level']),
      b('caps', 'Peak caps', true),
      f('glow', 'Glow', 0.6, 0, 2),
      f('reflection', 'Reflection', 1, 0, 1),
      f('floor', 'Floor grid', 1, 0, 1),
      f('background', 'Background', 1, 0, 1),
      f('release', 'Fall time', 0.14, 0.02, 1),
      f('punch', 'Kick punch', 0.1, 0, 0.4),
    ],
  },
  {
    kind: 'radialSpectrum',
    label: 'Radial spectrum',
    description: 'Spectrum wrapped around a circle: a ring of bars or a smooth blooming flower.',
    params: [
      e('style', 'Style', 'bars', ['bars', 'bloom']),
      i('bars', 'Bars', 96, 16, 256),
      f('radius', 'Radius', 0.22, 0.05, 0.6),
      f('length', 'Length', 0.25, 0, 0.6),
      f('thickness', 'Thickness', 0.55, 0.05, 1),
      i('symmetry', 'Symmetry', 2, 1, 8),
      f('spin', 'Spin', 0.1, -1, 1, 0.01, 'turns per phrase'),
      f('core', 'Core glow', 0.6, 0, 2),
      f('glow', 'Glow', 0.8, 0, 2),
      f('release', 'Fall time', 0.15, 0.02, 1),
      f('punch', 'Kick punch', 0.15, 0, 0.5),
    ],
  },
  {
    kind: 'barCity',
    label: '3D bar city',
    description: 'Spectrum history extruded into a city of glowing towers with a beat-synced flyover.',
    params: [
      i('columns', 'Columns', 32, 8, 64),
      i('rows', 'Rows', 40, 8, 64),
      f('height', 'Height', 1.4, 0.2, 3),
      f('speed', 'Scroll', 1, 0, 4, 0.01, 'rows per beat'),
      f('camHeight', 'Camera height', 1, 0.1, 3),
      f('swing', 'Camera swing', 0.3, 0, 1),
      f('gap', 'Gap', 0.25, 0, 0.8),
      f('fog', 'Fog', 0.5, 0, 1),
      f('windows', 'Windows', 0.6, 0, 1),
      f('glow', 'Glow', 1, 0, 2),
    ],
  },
  {
    kind: 'spectrogram',
    label: 'Spectrogram',
    description: 'Scrolling waterfall of the spectrum over time.',
    params: [
      e('direction', 'Direction', 'down', ['down', 'up', 'left', 'right']),
      f('speed', 'Speed', 1, 0.25, 4),
      f('contrast', 'Contrast', 1.4, 0.5, 3),
      f('floor', 'Floor', 0.25, 0, 0.8),
      f('glow', 'Glow', 0.4, 0, 2),
      f('perspective', 'Perspective', 0, 0, 1),
    ],
  },
  {
    kind: 'scope',
    label: 'Oscilloscope',
    description: 'Phosphor-style waveform, stereo vectorscope (Lissajous) or polar ring.',
    params: [
      e('mode', 'Mode', 'wave', ['wave', 'lissajous', 'circle']),
      f('thickness', 'Thickness', 3, 0.5, 12, 0.1),
      f('gain', 'Gain', 1.2, 0.2, 4),
      f('glow', 'Glow', 1, 0, 2),
      f('smoothing', 'Smoothing', 0.3, 0, 1),
      f('color', 'Colour', 0.6, 0, 1, 0.01, 'position in the palette'),
      f('radius', 'Radius', 0.28, 0.1, 0.5),
      f('length', 'Length', 1, 0.1, 1),
    ],
  },
  {
    kind: 'lines',
    label: 'Line work',
    description: 'Minimal line drawings: stacked ridge lines, displaced horizontals, concentric rings or streamlines flowing around a ball.',
    params: [
      e('mode', 'Mode', 'joy', ['joy', 'horizontal', 'radial', 'flow']),
      i('count', 'Lines', 36, 4, 80),
      f('amplitude', 'Amplitude', 0.5, 0, 1),
      f('thickness', 'Thickness', 1.5, 0.5, 6, 0.1),
      f('speed', 'Speed', 1, 0, 4),
      f('spread', 'Spread', 0.75, 0.2, 1),
      f('perspective', 'Perspective', 0.3, 0, 1),
      f('color', 'Colour', 0.85, 0, 1),
      f('glow', 'Glow', 0.3, 0, 2),
    ],
  },
  {
    kind: 'polygon',
    label: 'Shape play',
    description: 'Morphing polygons with N-fold radial instancing and nested, rotating recursion.',
    params: [
      f('sides', 'Sides', 6, 3, 12, 0.01),
      f('roundness', 'Roundness', 0, 0, 1),
      f('beatMorph', 'Beat morph', 0, 0, 1, 0.01, 'triangle → square → hexagon → circle on each beat'),
      f('size', 'Size', 0.25, 0.05, 0.6),
      i('copies', 'Copies', 1, 1, 12),
      f('spread', 'Spread', 0.25, 0, 0.5),
      i('nested', 'Nested', 1, 1, 12),
      f('nestScale', 'Nest scale', 0.78, 0.5, 0.95),
      f('nestOffset', 'Nest offset', 0, -1, 1, 0.01, 'slide each nested copy up or down (concentric → stacked)'),
      f('twist', 'Twist', 0.1, -1, 1),
      f('spin', 'Spin', 0.25, -2, 2, 0.01, 'turns per bar'),
      f('angle', 'Angle', 0, 0, 360, 1, 'static rotation in degrees (45 turns the diamond into a square)'),
      f('offsetY', 'Offset Y', 0, -0.5, 0.5, 0.005, 'move the shape up or down'),
      f('stroke', 'Stroke', 0.012, 0, 0.1, 0.001, '0 = filled'),
      f('fill', 'Fill', 0, 0, 1),
      f('glow', 'Glow', 0.6, 0, 2),
      f('pulse', 'Kick pulse', 0.15, 0, 0.5),
      f('colorSpread', 'Colour spread', 0.6, 0, 1),
      f('background', 'Background', 0.3, 0, 1),
    ],
  },
  {
    kind: 'swissGrid',
    label: 'Swiss grid',
    description: 'International-style modular grid: columns, blocks and dots driven by the EQ.',
    params: [
      e('mode', 'Mode', 'bars', ['bars', 'blocks', 'dots']),
      i('cols', 'Columns', 8, 2, 24),
      i('rows', 'Rows', 5, 2, 16),
      f('margin', 'Margin', 0.06, 0, 0.2),
      f('gutter', 'Gutter', 0.01, 0, 0.05, 0.001),
      f('accent', 'Accent', 0.5, 0, 1),
      f('lines', 'Grid lines', 0.6, 0, 1),
      f('shift', 'Bar shift', 0.5, 0, 1),
      b('paper', 'Paper (light)', true),
    ],
  },
  {
    kind: 'tiles',
    label: 'Tiles',
    description: 'Bauhaus primitives or Truchet tiles that flip on hats, snares or beats.',
    params: [
      e('style', 'Style', 'bauhaus', ['bauhaus', 'truchet', 'arcs']),
      i('cells', 'Cells', 6, 2, 24),
      e('flipOn', 'Flip on', 'hat', ['hat', 'snare', 'kick', 'beat', 'bar']),
      f('flipAmount', 'Flip amount', 0.35, 0, 1),
      f('ease', 'Flip time', 0.5, 0.05, 1),
      f('stroke', 'Stroke', 0.12, 0.02, 0.4),
      i('colors', 'Colours', 4, 2, 5),
      f('pulse', 'Zoom pulse', 0.05, 0, 0.3),
    ],
  },
  {
    kind: 'memphis',
    label: 'Memphis',
    description: 'Confetti of squiggles, zigzags, dots and solids that hop on the beat.',
    params: [
      f('density', 'Density', 1, 0.2, 2),
      f('scale', 'Scale', 1, 0.3, 2),
      f('drift', 'Drift', 0.4, 0, 2),
      f('jitter', 'Beat hop', 0.4, 0, 1),
      f('squiggle', 'Squiggles', 0.5, 0, 1),
      f('outline', 'Outlines', 0.5, 0, 1),
      f('background', 'Background', 1, 0, 1),
    ],
  },
  {
    kind: 'kineticType',
    label: 'Kinetic type',
    description: 'Your text, animated to the beat: stacked marquees, punches, a word per beat, a corner-chasing bounce or a receding space crawl.',
    params: [
      t('text', 'Text', 'BOOFVIZ', 'Separate words with spaces or "/"'),
      e('source', 'Text from', 'text', ['text', 'lyrics', 'title'], 'lyrics: the line being sung (Spotify) · title: song and artist · falls back to Text when nothing is playing'),
      e('mode', 'Mode', 'stack', ['stack', 'punch', 'words', 'marquee', 'bounce', 'crawl'], 'bounce: screensaver logo · crawl: lines split by "/" scroll into the distance'),
      e('font', 'Font', 'heavy', ['heavy', 'condensed', 'mono', 'serif', 'marker']),
      i('rows', 'Rows', 5, 1, 12),
      f('speed', 'Speed', 1, -4, 4, 0.01, 'text widths per 4 beats'),
      f('size', 'Size', 0.8, 0.2, 1.5),
      f('stretch', 'Bass stretch', 0.3, 0, 1),
      f('outline', 'Outline rows', 0.5, 0, 1),
      i('wordBeats', 'Beats per word', 1, 1, 16),
      f('skew', 'Skew', 0, -0.5, 0.5),
      f('punch', 'Kick punch', 0.2, 0, 0.6),
    ],
  },
  {
    kind: 'lyricVideo',
    label: 'Lyric video',
    description: 'Music-video lyrics: every letter is its own 3D object that drops, slams, shuffles, flips, spins, flies through the camera or orbits on the sung timing of its word, with extruded depth and crisp edges at any size.',
    params: [
      e('style', 'Style', 'auto', ['auto', 'drop', 'slam', 'pop', 'shuffle', 'flip', 'spin3d', 'zoomthrough', 'stack', 'wave', 'glitch', 'scatter', 'orbit3d', 'highway', 'credits', 'infomercial', 'ransom', 'teletext', 'screensaver', 'neonalley', 'jcard', 'laser', 'highscore', 'explosion', 'shatterdrop', 'jelly', 'glitter'], 'auto: picks a style that suits the look'),
      e('material', 'Letters made of', 'auto', ['auto', 'plain', 'chrome', 'neon', 'paper', 'led', 'phosphor', 'stencil', 'mimeo', 'rubdown', 'laser', 'holo', 'jelly', 'melt']),
      f('melt', 'Melt', 0.7, 0, 1.4, 0.01, 'melting letters: how far they sag and drip'),
      f('hero', 'Hero word', 0.6, 0, 1, 0.01, 'the key word of each line takes the frame (bigger in the chorus)'),
      f('camera', 'Camera moves', 0.5, 0, 1, 0.01, 'push-ins, whip-pans into new lines, chorus orbits, punch-ins'),
      f('drama', 'Song shape', 0.7, 0, 1, 0.01, 'how much verses stay calm and choruses and drops go big'),
      e('exit', 'Lines leave by', 'auto', ['auto', 'style', 'fade', 'shatter', 'burn']),
      e('source', 'Words from', 'lyrics', ['lyrics', 'title', 'text'], 'lyrics: the sung line (song title before the first line) · text: your own words below'),
      t('text', 'Text', 'BOOFVIZ / LYRIC VIDEO', 'Your own lines, separated by "/" (used when nothing is playing)'),
      i('lineBeats', 'Beats per line', 8, 1, 32, 'how long each of your own lines stays up'),
      e('font', 'Font', 'heavy', ['heavy', 'condensed', 'mono', 'serif', 'marker']),
      f('size', 'Size', 1, 0.3, 2.5),
      e('position', 'Position', 'center', ['center', 'lower', 'upper']),
      f('depth', 'Depth', 0.5, 0, 1, 0.01, 'extruded 3D thickness'),
      f('outline', 'Outline', 0, 0, 1),
      f('glow', 'Glow', 0.2, 0, 2),
      f('shadow', 'Shadow', 0.6, 0, 1, 0.01, 'dark soft edge that keeps words readable over busy looks'),
      e('colorMode', 'Colour', 'palette', ['palette', 'gradient', 'white', 'rainbow']),
      f('dimPast', 'Dim sung words', 0.25, 0, 1),
      f('speed', 'Speed', 1, 0.25, 3, 0.01, 'animation speed'),
      f('punch', 'Kick punch', 1, 0, 3),
      i('lead', 'Lead (ms)', 120, -500, 1000, 'words arrive this much before they are sung'),
      b('uppercase', 'Uppercase', true),
    ],
  },
  {
    kind: 'lyrics',
    label: 'Lyrics',
    description: 'Synced lyrics of the track playing now: a karaoke sweep, lines that punch in on the beat, or a typewriter with a blinking cursor.',
    params: [
      e('mode', 'Mode', 'karaoke', ['karaoke', 'punch', 'typewriter'], 'karaoke: fill sweeps across the line · punch: each line slams in · typewriter: characters type out'),
      e('font', 'Font', 'heavy', ['heavy', 'condensed', 'mono', 'serif', 'marker']),
      f('size', 'Size', 0.8, 0.3, 1.6),
      e('position', 'Position', 'lower', ['center', 'lower', 'upper']),
      f('punch', 'Kick punch', 0.3, 0, 1),
      f('glow', 'Glow', 0.6, 0, 2),
      f('outline', 'Outline', 0.6, 0, 1),
      f('backdrop', 'Backdrop', 0.35, 0, 1, 0.01, 'dark plate behind the text for readability on a projector'),
      i('lead', 'Lead (ms)', 150, -500, 1000, 'lines appear this much before they are sung'),
      b('uppercase', 'Uppercase', false),
      f('nextLine', 'Next line', 0.45, 0, 1, 0.01, 'opacity of the upcoming line'),
      b('titleCard', 'Title card', true, '"Title — Artist" at each track start and when there are no synced lyrics'),
      t('idleText', 'Idle text', '', 'shown when nothing is playing'),
    ],
  },
  {
    kind: 'prism',
    label: 'Prism',
    description: 'A white beam enters a glass triangle and fans out into a rainbow, each colour lit by its frequency band.',
    params: [
      f('size', 'Size', 0.28, 0.1, 0.5),
      f('spread', 'Spread', 0.5, 0, 1),
      f('beam', 'Beam', 1, 0, 2),
      f('glow', 'Glow', 0.8, 0, 2),
      f('tilt', 'Tilt', 0, -0.3, 0.3),
      f('paletteMix', 'Palette tint', 0, 0, 1, 0.01, '0 = true rainbow · 1 = palette colours'),
    ],
  },
  {
    kind: 'synthSunset',
    label: 'Synth sunset',
    description: 'Striped sun over spectrum mountains and a neon grid that scrolls with the beat.',
    params: [
      f('sun', 'Sun size', 0.22, 0.05, 0.45),
      i('stripes', 'Sun stripes', 9, 0, 20),
      f('horizon', 'Horizon', 0.42, 0.2, 0.7),
      f('mountains', 'Mountains', 1, 0, 2),
      f('glow', 'Glow', 1, 0, 2),
      f('stars', 'Stars', 1, 0, 2),
    ],
  },
  {
    kind: 'opArt',
    label: 'Op art',
    description: 'Optical-illusion patterns: flowing black-and-white waves, a bulging checkerboard or moiré rings.',
    params: [
      e('mode', 'Mode', 'waves', ['waves', 'bulge', 'moire']),
      f('frequency', 'Frequency', 1, 0.3, 3),
      f('amplitude', 'Amplitude', 0.6, 0, 1.5),
      f('contrast', 'Contrast', 1, 0.2, 2),
      f('colorize', 'Colourise', 0, 0, 1, 0.01, '0 = black & white · 1 = palette'),
      f('motion', 'Motion', 1, 0, 3),
    ],
  },
  {
    kind: 'dots',
    label: 'Dots',
    description: 'An infinite polka-dot field that zooms forever, or a composition of floating circles sized by the EQ.',
    params: [
      e('mode', 'Mode', 'polka', ['polka', 'circles']),
      f('density', 'Density', 1, 0.3, 3),
      f('size', 'Size', 1, 0.3, 2),
      f('pulse', 'Pulse', 0.5, 0, 1.5),
      f('drift', 'Drift', 1, 0, 3),
      f('zoom', 'Zoom', 1, 0.5, 2),
    ],
  },
  {
    kind: 'glassMeadow',
    label: 'Glass meadow',
    description: 'Glossy aero wallpaper world: a swaying green hill under a cumulus sky, glass orbs drifting up and refracting it, bubbles, light ribbons, a lens flare and dew on the lens.',
    params: [
      e('timeOfDay', 'Time of day', 'cycle', ['cycle', 'day', 'dusk', 'morning', 'noon', 'golden', 'twilight'], 'cycle: morning → noon → golden hour → twilight, one step per phrase · day / dusk alternate two'),
      i('orbs', 'Orbs', 14, 0, 24),
      f('orbSize', 'Orb size', 1, 0.5, 1.8),
      f('rise', 'Rise speed', 1, 0, 3),
      b('heroOrb', 'Downbeat orb', true, 'a big orb bounces up on every bar'),
      f('refraction', 'Refraction', 1, 0, 2),
      f('bubbles', 'Bubbles', 1, 0, 2),
      f('sway', 'Grass sway', 1, 0, 2),
      f('clouds', 'Clouds', 1, 0, 2),
      f('aurora', 'Light ribbons', 1, 0, 2),
      f('flare', 'Lens flare', 1, 0, 2),
      f('dew', 'Dew', 0.35, 0, 1),
      f('burst', 'Drop burst', 1, 0, 1, 0.01, 'orbs burst into droplets on the lens when the drop hits'),
      e('quality', 'Quality', 'high', ['high', 'low'], 'low: no grass blades, lighter clouds'),
    ],
  },
  {
    kind: 'deStijl',
    label: 'De Stijl',
    description: 'Black-ruled grid of primaries and white, re-drawn on the bar or phrase, cells flashing with the bands.',
    params: [
      i('cells', 'Cells', 11, 3, 30),
      f('color', 'Colour', 0.35, 0, 1, 0.01, 'share of coloured cells'),
      f('line', 'Line width', 0.012, 0.002, 0.04, 0.001),
      e('reshuffle', 'Re-draw', 'phrase', ['bar', 'phrase', 'off']),
    ],
  },
  {
    kind: 'pixelArcade',
    label: 'Pixel arcade',
    description: 'Self-playing retro games that move on the beat: falling blocks, a pellet maze, an alien invasion, paddle tennis, a snake and light-cycle racers.',
    params: [
      e('mode', 'Game', 'blocks', ['blocks', 'maze', 'aliens', 'paddle', 'snake', 'racers']),
      f('speed', 'Speed', 1, 0.25, 4, 0.05, 'game ticks per beat ×'),
      i('cycleBars', 'Restart every', 16, 2, 64, 'bars per game (replays identically in every window)'),
      f('glow', 'Glow', 1, 0, 2),
      f('paletteMix', 'Palette tint', 0, 0, 1, 0.01, '0 = classic colours · 1 = palette'),
      f('scanlines', 'Scanlines', 0.3, 0, 1),
    ],
  },
  {
    kind: 'demoParts',
    label: 'Demo parts',
    description:
      'A 320×256, 32-colour home-computer megademo: plasma with colour cycling, a rotozoomer, a textured tunnel and shaded vector balls in phrase-long parts joined by raster wipes, with a bitmap sine scroller and copper bars running through the borders.',
    params: [
      t('text', 'Text', 'BOOFVIZ', 'sine-scroller text; the vector balls spell its first word'),
      e('source', 'Text from', 'text', ['text', 'lyrics', 'title'], 'lyrics: the line being sung · title: song and artist · falls back to Text'),
      e('part', 'Part', 'sequence', ['sequence', 'plasma', 'rotozoom', 'tunnel', 'balls'], 'sequence: the next part every phrase · or hold one part'),
      i('partPhrases', 'Phrases per part', 1, 1, 8),
      f('wipeBeats', 'Wipe length', 2, 0.25, 8, 0.25, 'beats; the raster wipe finishes on the phrase downbeat'),
      e('scroller', 'Scroller', 'band', ['band', 'over', 'off'], 'band: its own strip under the effect · over: across the effect'),
      f('scrollSpeed', 'Scroll speed', 40, 0, 160, 1, 'pixels per beat at 320×256'),
      f('wave', 'Scroller wave', 1, 0, 2, 0.01, 'sine height ×; a new wave on every downbeat'),
      i('bars', 'Copper bars', 7, 0, 12, 'doubled while the track builds'),
      f('copperSpeed', 'Copper swing', 1, 0, 4, 0.01, 'swings per two bars'),
      f('jump', 'Kick jump', 1, 0, 2),
      f('rainbow', 'Rainbow copper', 1, 0, 1, 0.01, '0 = palette colours · 1 = full rainbow'),
      f('copperGlow', 'Copper brightness', 1, 0.3, 2),
      i('cycleStep', 'Cycle notch', 2, 0, 8, 'palette-cycling steps per beat'),
      f('cycleRate', 'Cycle drift', 8, 0, 40, 0.5, 'extra cycling steps per second'),
      f('stars', 'Star speed', 1, 0, 4),
      f('pump', 'Ball pump', 1, 0, 3, 0.01, 'kick pump × (1 = 4 %)'),
      f('explode', 'Drop burst', 1, 0, 2),
      f('shake', 'Drop shake', 1, 0, 3, 0.01, 'whole-pixel playfield shake'),
      f('border', 'Border', 0.04, 0, 0.2, 0.005, 'top and bottom border (fraction of the height)'),
      f('scanlines', 'Raster lines', 0.35, 0, 1),
    ],
  },
  {
    kind: 'codeRain',
    label: 'Code rain',
    description: 'Falling columns of glowing glyphs with bright heads and fading tails; rain speeds up with the energy.',
    params: [
      e('glyphs', 'Glyphs', 'katakana', ['katakana', 'binary', 'hex', 'latin']),
      i('columns', 'Columns', 90, 20, 240),
      f('speed', 'Speed', 1, 0, 4),
      f('trail', 'Trail', 1, 0.2, 3),
      f('change', 'Glyph flicker', 4, 0, 20, 0.1, 'glyph changes per second'),
      f('glow', 'Glow', 1, 0, 2),
      b('mirror', 'Mirrored glyphs', true),
    ],
  },
  {
    kind: 'warp',
    label: 'Warp',
    description: 'Flying through stars: a calm starfield, a hyperspace jump that streaks on drops, or a slit-scan corridor of streaming light.',
    params: [
      e('mode', 'Mode', 'starfield', ['starfield', 'hyperspace', 'corridor']),
      f('speed', 'Speed', 1, 0, 4),
      f('density', 'Density', 1, 0.2, 3),
      f('streak', 'Streak', 0.3, 0, 1),
      f('twist', 'Twist', 0, -1, 1),
    ],
  },
  {
    kind: 'orb',
    label: 'Orb',
    description: 'A black hole with a lensed accretion disk, or a spinning mirror ball throwing beams around the room.',
    params: [
      e('mode', 'Mode', 'blackhole', ['blackhole', 'mirrorball']),
      f('size', 'Size', 1, 0.3, 2),
      f('spin', 'Spin', 1, -3, 3),
      f('tilt', 'Tilt', 0.3, 0, 1),
      f('beams', 'Beams', 1, 0, 2),
    ],
  },
  {
    kind: 'liquidChrome',
    label: 'Liquid chrome',
    description: 'Raymarched liquid-mercury blobs in a pale studio: they coalesce into one sphere through the bar and burst apart on the downbeat, droplets pinch off and orbit, and a drop turns the chrome into rainbow foil.',
    params: [
      e('formation', 'Formation', 'cycle', ['cycle', 'cluster', 'ring', 'stack'], 'cycle: cluster → ring → stack, one per phrase'),
      e('count', 'Burst into', 'cycle', ['cycle', '3', '5', '8'], 'blobs per burst; cycle: 3 → 5 → 8'),
      i('cycleBars', 'Coalesce every', 1, 1, 4, 'bars: merges into one sphere by the last beat, bursts on the downbeat'),
      i('droplets', 'Droplets', 4, 0, 4, 'one pinches off every second beat and joins the orbit'),
      f('size', 'Size', 1, 0.6, 1.4),
      f('goo', 'Goo', 0.34, 0.1, 0.7, 0.01, 'smooth-min radius: how sticky the necks are (grows through builds)'),
      f('punch', 'Kick wobble', 1, 0, 2, 0.01, '1 = a 6% jelly pulse on every beat'),
      f('ripple', 'Snare ripple', 1, 0, 2),
      f('spin', 'Spin', 0.15, -1, 1, 0.01, 'turns per 4 bars'),
      f('iridescence', 'Thin film', 0.6, 0, 1, 0.01, 'oil-on-water rainbow at grazing angles'),
      f('holo', 'Drop foil', 1, 0, 1, 0.01, 'rainbow-foil chrome and a lit grid for about two bars after a drop'),
      f('room', 'Studio light', 1, 0, 1, 0.01, '0 = dark club, 1 = pale icy studio'),
      f('grid', 'Floor grid', 0.7, 0, 2),
      f('mirror', 'Floor mirror', 0.6, 0, 1),
      f('starburst', 'Starburst', 0.6, 0, 1.5, 0.01, 'turns slowly behind the camera; seen mirrored in the metal'),
      e('quality', 'Quality', 'high', ['low', 'medium', 'high'], 'low: 0.75× internal scale and fewer ray steps for integrated GPUs'),
    ],
  },
  {
    kind: 'ricochet',
    label: 'Ricochet lines',
    description: 'Screensaver-style polygons whose corners bounce off the edges, echoed as a fading trail.',
    params: [
      i('shapes', 'Shapes', 2, 1, 4),
      i('vertices', 'Corners', 4, 2, 8),
      i('trail', 'Echoes', 6, 1, 16),
      f('gap', 'Echo gap', 0.08, 0.01, 0.3),
      f('speed', 'Speed', 1, 0, 4),
      f('thickness', 'Thickness', 1.6, 0.5, 6, 0.1),
      f('glow', 'Glow', 1, 0, 2),
    ],
  },
  {
    kind: 'twistCube',
    label: 'Twist cube',
    description: 'A 3×3 twisting puzzle cube: a slice turn on every beat, scrambling and then solving itself exactly on the phrase, tumbling on the bar and bursting apart on drops.',
    params: [
      e('style', 'Finish', 'stickers', ['stickers', 'candy', 'chrome'], 'stickers: black body · candy: stickerless gloss · chrome: mirror body'),
      e('colors', 'Colours', 'classic', ['classic', 'palette']),
      i('turnsPerBar', 'Turns per bar', 4, 1, 8),
      i('cyclePhrases', 'Solve every', 1, 1, 4, 'phrases: scrambles through the first half, solved on the last beat'),
      f('snap', 'Snap', 0.35, 0.1, 1, 0.01, 'turn time as a share of the beat slot'),
      b('slices', 'Middle slices', true),
      b('tumble', 'Bar tumble', true),
      f('spin', 'Spin', 0.15, -1, 1, 0.01, 'turns per 4 bars'),
      f('size', 'Size', 1, 0.5, 1.6),
      f('punch', 'Kick punch', 0.06, 0, 0.3),
      f('explode', 'Drop burst', 1.2, 0, 3),
      f('round', 'Roundness', 0.12, 0.02, 0.3),
      f('glow', 'Rim light', 0.6, 0, 2),
      f('shadow', 'Shadow', 0.6, 0, 1),
      f('tilt', 'Camera tilt', 0.45, 0, 1.2),
    ],
  },
  {
    kind: 'background',
    label: 'Background',
    description: 'Palette gradient backdrop with slow drift and a kick lift.',
    params: [
      e('style', 'Style', 'vertical', ['vertical', 'radial', 'diagonal', 'noise']),
      f('from', 'From', 0, 0, 1),
      f('to', 'To', 0.4, 0, 1),
      f('intensity', 'Intensity', 0.6, 0, 2),
      f('motion', 'Motion', 0.2, 0, 1),
      f('pulse', 'Kick lift', 0.2, 0, 1),
    ],
  },
  {
    kind: 'lostScene',
    label: 'Lost-media set',
    description: 'Procedural sets for found footage: colour bars, a test card, a transmitter at sign-off, a weather radar, a birthday cake, a public-access studio, a kids-show puppet, mall CCTV, a summer lake, a corporate globe, karaoke scenery, a shortwave radio, a silent-film card, a CD-ROM desktop and a web video player.',
    params: [
      e('scene', 'Set', 'bars', ['bars', 'testcard', 'tower', 'radar', 'candles', 'studio', 'puppet', 'cctv', 'lake', 'globe', 'scenic', 'shortwave', 'intertitle', 'desktop', 'player']),
      i('variant', 'Variant', 0, 0, 3),
      f('react', 'Music reaction', 1, 0, 2),
      f('tint', 'Palette tint', 0, 0, 1),
      f('eerie', 'Eerie', 0, 0, 1),
      f('spin', 'Spin', 0, 0, 3),
    ],
  },
  {
    kind: 'broadcast',
    label: 'Broadcast text',
    description: 'What an old recording printed on screen: camcorder REC and date stamp, VCR display (follows the tape events), channel bug and lower third with the playing song, CCTV labels, a weather list, corporate titles, numbers-station groups, a test-card ID, a sign-off card or a web player. Lyrics can show as closed captions, teletext, a karaoke wipe, a silent-film intertitle or a handwritten slate.',
    params: [
      e('kit', 'Kit', 'camcorder', ['camcorder', 'vcr', 'tv', 'cctv', 'weather', 'corporate', 'shortwave', 'test', 'signoff', 'web', 'desktop', 'archive', 'channel', 'none']),
      e('captions', 'Lyrics as', 'off', ['off', 'cc', 'teletext', 'karaoke', 'intertitle', 'slate']),
      f('lyrics', 'Lyrics on', 1, 0, 1, 1, 'turn the lyric captions off (0) or on (1)'),
      b('safe43', '4:3 safe area', false, 'keep text inside the middle 4:3 (for looks on an old TV set)'),
      t('date', 'Date stamp', 'JUN 14 1994'),
      t('station', 'Station / bug', 'CHANNEL 9', 'your channel name or brand'),
      t('title', 'Title', '', 'title cards, slates and captions when nothing is playing'),
      t('ticker', 'Ticker', ''),
      f('events', 'Tape events', 0, 0, 1, 0.01, 'match the Lost tape effect so the display agrees'),
      t('eventList', 'Events', 'all'),
      i('seed', 'Tape', 0, 0, 99),
      i('lead', 'Lyrics lead (ms)', 150, -500, 1000),
    ],
  },
  {
    kind: 'archiveFootage',
    label: 'Archive footage',
    description: 'Real old films and TV from the Internet Archive (before 2003): a random clip every few bars, downloaded once and cached, kept in step with the beat. Optional jump cuts to a new moment every few beats.',
    params: [
      e('collection', 'Collection', 'ephemeral', ['ephemeral', 'newsreels', 'classictv', 'cartoons', 'government', 'space', 'homemovies', 'commercials', 'custom', 'myvideos'], 'myvideos: your own clips from the BOOFVIZ videos folder (Master tab)'),
      t('channels', 'Surf channels', '', 'channel surfing: a list of collections, e.g. cartoons, classictv, commercials (empty = just the collection above)'),
      e('decade', 'Decade', 'any', ['any', '30s', '40s', '50s', '60s', '70s', '80s', '90s', '00s'], 'any = the years below'),
      t('search', 'Search words', '', 'narrow the collection, e.g. dance, cars, television (My search: any query)'),
      i('yearFrom', 'From year', 1930, 1880, 2002),
      i('yearTo', 'To year', 2002, 1880, 2002),
      i('changeBars', 'New clip every (bars)', 16, 1, 64),
      i('jumpBeats', 'Jump cut every (beats)', 0, 0, 16, '0 = play straight through'),
      i('skip', 'Next clip', 0, 0, 99, 'bump to change clip now'),
      e('fit', 'Fit', 'cover', ['cover', 'contain']),
      f('punch', 'Kick zoom', 0.3, 0, 1),
      f('switchStatic', 'Channel-change static', 0, 0, 1),
    ],
  },
  {
    kind: 'screensaver90',
    label: '90s screensaver',
    description: 'Old desktop screensavers: walking a brick 3D maze (turning at corners and dead ends), winged floppy disks flapping across the screen on the beat, bouncing line polygons with trails, or a rave-flyer fractal with an acid smiley.',
    params: [
      e('scene', 'Screensaver', 'maze', ['maze', 'flyers', 'polylines', 'fractal']),
      f('speed', 'Walk speed', 1, 0, 4),
      i('count', 'Flyers', 12, 1, 18),
      f('smiley', 'Smiley', 0, 0, 1.5),
      f('zoom', 'Fractal zoom', 1, 0.3, 4),
      f('react', 'Music reaction', 1, 0, 2),
      i('seed', 'Maze', 0, 0, 99),
    ],
  },
  {
    kind: 'pipes',
    label: '3D pipes',
    description: 'The 3D pipes screensaver: shiny pipes grow through space a segment at a time on the beat, with ball joints at the turns, then the screen clears and starts again.',
    params: [i('pipes', 'Pipes', 7, 1, 12), f('rate', 'Segments per beat', 4, 0.25, 16), i('clearBars', 'Clear every (bars)', 32, 2, 128), f('drift', 'Camera drift', 0.3, 0, 2), f('punch', 'Kick punch', 1, 0, 3), i('seed', 'Seed', 0, 0, 99)],
  },
  {
    kind: 'lowPoly',
    label: '32-bit console',
    description: 'A low-poly canyon flythrough like a 32-bit console game: rendered at 240 lines with chunky pixels, wobbling vertices, 15-bit dithered colour, fog, and rings to fly through that pulse on the kick.',
    params: [i('lines', 'Lines', 240, 120, 480), f('speed', 'Speed', 1, 0, 4), f('wobble', 'Vertex wobble', 0.6, 0, 1), f('punch', 'Kick punch', 1, 0, 3)],
  },
  {
    kind: 'desktop90',
    label: '90s desktop',
    description: 'A late-90s home computer, drawn chunky: a homemade web page (tiled stars, rainbow title, under-construction banner, marquee, hit counter), a desktop filling up with error boxes on the beat, a pager, or a virtual pet. Lyrics go in the marquee, the error boxes and the pager.',
    params: [
      e('mode', 'Screen', 'web', ['web', 'popups', 'pager', 'pet', 'jcard']),
      e('source', 'Words from', 'lyrics', ['lyrics', 'text']),
      t('text', 'Text', 'Thanks for visiting! Sign my guestbook!'),
      t('title', 'Page title', 'Welcome to my Homepage!'),
      i('every', 'New box every (beats)', 2, 1, 16),
      f('speed', 'Marquee speed', 1, 0, 4),
      f('react', 'Music reaction', 1, 0, 2),
      i('lead', 'Lyrics lead (ms)', 150, -500, 1000),
    ],
  },
  {
    kind: 'musicChannel',
    label: 'Music channel',
    description: 'The song you are playing as TV: a cable music channel now-playing screen (album art, title, artist, album, progress bar, channel bug, a rotating panel with the sung line), or the album art itself filling the screen with a slow pan and zoom.',
    params: [
      e('layout', 'Layout', 'cable', ['cable', 'art']),
      e('style', 'Era', 'cable90', ['cable90', 'digital00']),
      t('channel', 'Channel name', 'RETRO ALTERNATIVE'),
      i('number', 'Channel number', 812, 1, 999),
      e('fit', 'Art fit', 'cover', ['cover', 'contain']),
      f('pan', 'Pan & zoom', 1, 0, 2),
      f('punch', 'Kick punch', 1, 0, 3),
      t('title', 'Title (nothing playing)', 'Your Song Here'),
      t('artist', 'Artist (nothing playing)', 'Now Playing'),
    ],
  },
  {
    kind: 'vitalSigns',
    label: 'Vital signs monitor',
    description: 'A bedside patient monitor: ECG, pleth and respiration traces sweeping across with phosphor persistence, one heartbeat per beat, the heart rate reading the live BPM, and a flatline alarm on the drop before it restarts.',
    params: [f('glow', 'Phosphor glow', 1, 0, 2), b('flatline', 'Flatline on the drop', true), t('patient', 'Label', 'BED 04')],
  },
  {
    kind: 'platinumStage',
    label: 'Platinum stage',
    description: 'A two-step garage club stage: folded velvet, sweeping beams, spinning chrome rings and diamond glints that fire on the swung two-step accents (not on every kick). Put a chrome name or lyric layer on top.',
    params: [f('swing', 'Swing', 0.6, 0, 1), f('glints', 'Glint size', 1, 0, 2), f('beams', 'Beams', 1, 0, 2), f('rings', 'Rings', 1, 0, 1), f('velvet', 'Velvet', 1, 0, 1.5)],
  },
  {
    kind: 'concrete',
    label: 'Concrete age',
    description: 'Raw board-formed concrete: prefab panel blocks at night in the snow (windows lighting floor by floor on the beat), a monolith in fog with light slits, a parking spiral with stencilled level numbers, deck-access walkways with doors lighting in sequence, a water tower at dusk, a wall close-up, or an architect\u2019s section drawing. Slides: a projector changing view every few bars.',
    params: [
      e('scene', 'Scene', 'panels', ['panels', 'monolith', 'parking', 'walkways', 'watertower', 'wall', 'section', 'modern']),
      i('slides', 'Slide every (bars)', 0, 0, 16, '0 = stay on the scene'),
      f('speed', 'Camera speed', 1, 0, 4),
      f('lit', 'Windows lit', 0.6, 0, 1),
      f('snow', 'Snow', 1, 0, 2),
      f('view', 'Viewpoint', 0, 0, 1),
      f('warm', 'Warm light', 0.3, 0, 1),
      f('react', 'Music reaction', 1, 0, 2),
    ],
  },
  {
    kind: 'neoBrutal',
    label: 'Neo-brutal',
    description: 'Neo-brutal graphics: lyric cards slamming into a stack, a raw unstyled web page breaking on the beat, split-flap BPM/bar/beat/time numbers, a sticker bomb, an oversized mixer whose faders are the real bands, a monospace data dump, a wall of lyric marquees, or lyrics snapped into a Swiss grid.',
    params: [
      e('mode', 'Layout', 'cards', ['cards', 'html', 'numbers', 'stickers', 'eq', 'data', 'marquee', 'grid']),
      e('source', 'Words from', 'lyrics', ['lyrics', 'text']),
      t('text', 'Text', 'RAW / LOUD / HONEST / NO DECORATION', 'your own lines, split by "/"'),
      i('lineBeats', 'Beats per line (own text)', 8, 1, 32),
      b('uppercase', 'Uppercase', true),
      f('speed', 'Marquee speed', 1, 0, 4),
      i('lead', 'Lyrics lead (ms)', 120, -500, 1000),
    ],
  },
  {
    kind: 'neo90',
    label: 'Neo-90s novelty',
    description: 'Late-90s novelty surfaces with the lyrics in them: a holographic foil sticker with the line embossed in rainbow, a hidden-picture stereogram (cross your eyes and the words float out), a lenticular card flipping between two words, a lava lamp (or a wall of wax melting the words), or a ceiling of glow-in-the-dark stars spelling the line when the lights go off.',
    params: [
      e('scene', 'Surface', 'holo', ['holo', 'stereogram', 'lenticular', 'lava', 'stars']),
      e('words', 'Words', 'line', ['line', 'hero', 'off']),
      e('font', 'Font', 'heavy', ['heavy', 'condensed', 'serif', 'mono', 'marker']),
      f('react', 'Music reaction', 1, 0, 2),
      b('lamp', 'Lava: lamp (off = wax wall)', true),
      f('melt', 'Melt', 0.5, 0, 1),
      f('reveal', 'Stereogram reveal', 0, 0, 1, 0.01, 'shows the hidden words plainly'),
      e('source', 'Words from', 'lyrics', ['lyrics', 'text']),
      t('text', 'Text', 'HOLO / FOIL / SHINE', 'your own lines, split by "/"'),
      i('lineBeats', 'Beats per line (own text)', 8, 1, 32),
      b('uppercase', 'Uppercase', true),
      i('lead', 'Lyrics lead (ms)', 120, -500, 1000),
    ],
  },
  {
    kind: 'prints',
    label: 'Photo prints',
    description: 'Vintage photo prints: a disposable camera flashing snapshots onto a pile on the table (orange date stamp, frames-left counter, the lyrics written on in marker), a photo-booth strip shot four frames to the beat with every pose holding up a word, or one big instant photo developing and shaking with the line written underneath.',
    params: [
      e('mode', 'Camera', 'snapshot', ['snapshot', 'booth', 'instant']),
      i('every', 'New print every (bars)', 2, 1, 16),
      b('captions', 'Captions', true),
      f('react', 'Music reaction', 1, 0, 2),
      e('source', 'Words from', 'lyrics', ['lyrics', 'text']),
      t('text', 'Text', 'SAY CHEESE / ONE MORE / FLASH', 'your own lines, split by "/"'),
      i('lineBeats', 'Beats per line (own text)', 8, 1, 32),
      b('uppercase', 'Uppercase', true),
      i('lead', 'Lyrics lead (ms)', 120, -500, 1000),
    ],
  },
  {
    kind: 'tapeDeck',
    label: 'Tape deck',
    description: 'A late-80s double cassette deck dubbing a mix tape: reels turning with the tape moving across as the song plays, needle VU meters with peak lights, and a cyan dot-matrix display typing out the lyrics as they are sung over a spectrum analyser.',
    params: [
      e('finish', 'Finish', 'black', ['black', 'silver']),
      e('deckB', 'Deck B', 'dub', ['dub', 'idle']),
      t('label', 'Tape label', '', 'empty = the song title'),
      t('labelB', 'Deck B label', 'BLANK C90'),
      f('speed', 'Reel speed', 1, 0, 3),
      f('react', 'Music reaction', 1, 0, 2),
      e('source', 'Words from', 'lyrics', ['lyrics', 'text']),
      t('text', 'Text', 'SIDE A / TRACK ONE / PRESS PLAY', 'your own lines, split by "/"'),
      i('lineBeats', 'Beats per line (own text)', 8, 1, 32),
      b('uppercase', 'Uppercase', true),
      i('lead', 'Lyrics lead (ms)', 120, -500, 1000),
    ],
  },
  {
    kind: 'sketchScreen',
    label: 'Sketch screen',
    description: 'The red drawing toy with the grey screen and two white knobs: every lyric line drawn as one unbroken line, the stylus reaching each word as it is sung and the knobs turning with it, then the toy is shaken clear for the next line (and shaken hard on the drop).',
    params: [
      i('cols', 'Letters per row', 16, 6, 30),
      f('shake', 'Shake', 1, 0, 2),
      f('react', 'Music reaction', 1, 0, 2),
      e('source', 'Words from', 'lyrics', ['lyrics', 'text']),
      t('text', 'Text', 'DRAW / SHAKE / DRAW AGAIN', 'your own lines, split by "/"'),
      i('lineBeats', 'Beats per line (own text)', 8, 1, 32),
      b('uppercase', 'Uppercase', true),
      i('lead', 'Lyrics lead (ms)', 120, -500, 1000),
    ],
  },
  {
    kind: 'adjust',
    label: 'Everything below',
    description: 'An adjustment layer: its effects treat every layer underneath (put a tape deck or old film here to age the whole picture).',
    params: [],
  },
];

export const EFFECTS: ModuleDef[] = [
  {
    kind: 'feedback',
    label: 'Feedback trails',
    description: 'Re-feeds the previous frame with zoom, rotation and fade.',
    params: [
      f('amount', 'Amount', 0.85, 0, 0.98),
      f('zoom', 'Zoom', 0.01, -0.05, 0.05, 0.001),
      f('rotate', 'Rotate', 0, -0.05, 0.05, 0.001),
      f('shiftX', 'Shift X', 0, -0.02, 0.02, 0.001),
      f('shiftY', 'Shift Y', 0, -0.02, 0.02, 0.001),
      f('hueDrift', 'Hue drift', 0, -0.05, 0.05, 0.001),
      e('blend', 'Blend', 'max', ['max', 'add', 'screen']),
    ],
  },
  {
    kind: 'bloom',
    label: 'Bloom',
    description: 'Soft glow from bright areas (multi-scale).',
    params: [f('strength', 'Strength', 0.8, 0, 3), f('threshold', 'Threshold', 0.6, 0, 2), f('radius', 'Radius', 0.6, 0, 1), f('knee', 'Knee', 0.5, 0, 1)],
  },
  {
    kind: 'mirror',
    label: 'Mirror',
    description: 'Reflect the image horizontally, vertically or into quadrants.',
    params: [e('mode', 'Mode', 'horizontal', ['horizontal', 'vertical', 'quad']), b('flip', 'Flip side', false)],
  },
  {
    kind: 'kaleidoscope',
    label: 'Kaleidoscope',
    description: 'N-fold mirror symmetry around the centre.',
    params: [i('segments', 'Segments', 6, 2, 16), f('spin', 'Spin', 0.05, -1, 1, 0.01, 'turns per bar'), f('zoom', 'Zoom', 1, 0.5, 2), f('angle', 'Angle', 0, 0, 1)],
  },
  {
    kind: 'rgbSplit',
    label: 'RGB split',
    description: 'Chromatic aberration: offsets the red and blue channels.',
    params: [f('amount', 'Amount', 0.006, 0, 0.05, 0.0005), f('angle', 'Angle', 0, 0, 1), f('radial', 'Radial', 0.5, 0, 1)],
  },
  {
    kind: 'gradientMap',
    label: 'Gradient map',
    description: 'Maps brightness onto the current palette.',
    params: [f('mix', 'Mix', 1, 0, 1), f('offset', 'Offset', 0, 0, 1), f('contrast', 'Contrast', 1, 0.5, 3)],
  },
  {
    kind: 'grade',
    label: 'Colour grade',
    description: 'Exposure, contrast, saturation, hue and temperature.',
    params: [f('exposure', 'Exposure', 0, -2, 2), f('contrast', 'Contrast', 1, 0.5, 2), f('saturation', 'Saturation', 1, 0, 2), f('hue', 'Hue', 0, -180, 180, 1), f('temperature', 'Temperature', 0, -1, 1)],
  },
  {
    kind: 'vignette',
    label: 'Vignette',
    description: 'Darkens the edges to focus the centre.',
    params: [f('amount', 'Amount', 0.4, 0, 1), f('size', 'Size', 0.8, 0.2, 1.5), f('softness', 'Softness', 0.5, 0.05, 1)],
  },
  {
    kind: 'grain',
    label: 'Film grain',
    description: 'Animated luminance grain.',
    params: [f('amount', 'Amount', 0.05, 0, 0.3), f('size', 'Size', 1, 0.5, 3)],
  },
  {
    kind: 'halftone',
    label: 'Halftone',
    description: 'Print screen: colour dots, comic-book ink on paper, or four-colour CMYK rosettes.',
    params: [e('mode', 'Mode', 'color', ['color', 'ink', 'cmyk']), f('cell', 'Dot size', 8, 3, 40, 0.5), f('angle', 'Angle', 45, 0, 90, 1), f('mix', 'Mix', 1, 0, 1)],
  },
  {
    kind: 'ledScreen',
    label: 'LED wall',
    description: 'Re-samples the image onto a grid of glowing round LEDs.',
    params: [f('cell', 'LED size', 10, 3, 40, 0.5), f('gap', 'Gap', 0.12, 0, 0.6), f('glow', 'Glow', 1, 0, 2)],
  },
  {
    kind: 'popGrid',
    label: 'Pop-art grid',
    description: 'Repeats the image in a grid of posterised tiles, each screen-printed in its own colour scheme.',
    params: [i('tiles', 'Tiles', 2, 1, 6), f('hueStep', 'Hue step', 1.2, 0, 3.14), i('levels', 'Levels', 4, 2, 8)],
  },
  {
    kind: 'retroPalette',
    label: 'Old hardware',
    description: 'Chunky pixels squeezed into the colours of an old machine (4-colour PC, amber or green monitor, teletext, 1-bit desktop, handheld LCD, or the colours of the current look) with ordered dithering.',
    params: [e('palette', 'Machine', 'cga', ['cga', 'ega', 'amber', 'green', 'teletext', 'mono', 'lcd', 'look']), f('pixel', 'Pixel size', 4, 1, 16, 0.5), f('dither', 'Dither', 1, 0, 1.5)],
  },
  {
    kind: 'vhs',
    label: 'Worn tape',
    description: 'A played-to-death video tape: line jitter, wobble, a rolling tracking band, head-switching noise at the bottom, colour bleed and tape grain.',
    params: [f('amount', 'Wear', 1, 0, 2), f('tracking', 'Tracking band', 0.5, 0, 1), f('noise', 'Noise', 0.6, 0, 1.5), f('bleed', 'Colour bleed', 1, 0, 2)],
  },
  {
    kind: 'tapeStack',
    label: 'Lost tape',
    description: 'A real tape deck: limited luma and colour bandwidth, generation loss, dropouts, head-switching noise, and tape events on the bar line (rewind, fast-forward, pause, signal loss, tape eat, recorded-over, focus hunting).',
    params: [
      e('format', 'Format', 'vhs', ['vhs', 'betamax', 'hi8', 'cable', 'broadcast']),
      i('generation', 'Copy generation', 2, 1, 8, '1 = master · 8 = a copy of a copy of a copy'),
      f('wear', 'Wear', 1, 0, 2),
      f('events', 'Tape events', 0.3, 0, 1, 0.01, 'how often something happens to the tape'),
      t('eventList', 'Events', 'all', 'comma list: rewind, ffwd, pause, signal, eat, overwrite, focus'),
      f('overwrite', 'Recorded over', 0, 0, 1, 0.01, 'an older recording bleeding through'),
      f('mood', 'Mood', 0.3, 0, 1, 0.01, '0 cozy · 0.5 neutral · 1 eerie'),
      i('seed', 'Tape', 0, 0, 99, 'which tape: changes where the damage falls'),
    ],
  },
  {
    kind: 'filmStock',
    label: 'Old film',
    description: 'Projected film: stepped home-movie frame rate, gate weave, grain, dust, hair, scratches, lamp flicker, faded dyes, light leaks, nitrate decay, splices and an optional overscan with sprocket holes.',
    params: [
      e('stock', 'Stock', 'super8', ['super8', '16mm', '35mm', 'nitrate']),
      e('tone', 'Tone', 'color', ['color', 'bw', 'sepia']),
      i('fps', 'Frame rate', 18, 0, 30, '0 = smooth'),
      f('wear', 'Wear', 1, 0, 2),
      f('weave', 'Gate weave', 1, 0, 3),
      f('dust', 'Dust', 1, 0, 2),
      f('flicker', 'Flicker', 1, 0, 2),
      f('fade', 'Colour fade', 0.3, 0, 1),
      f('leaks', 'Light leaks', 0.3, 0, 1.5),
      f('splices', 'Splices', 0.2, 0, 1),
      b('gate', 'Show film edge', false),
      i('seed', 'Reel', 0, 0, 99),
    ],
  },
  {
    kind: 'print2',
    label: 'Two-colour print',
    description: 'A cheap two-colour print: the picture split into two inks with their own halftone screens, slightly misregistered (more on the kick), on grainy paper.',
    params: [e('inks', 'Inks', 'red-black', ['red-black', 'blue-pink', 'green-orange', 'black-yellow', 'look']), f('misregister', 'Misregistration', 1, 0, 4), f('dot', 'Dot size', 6, 2, 24, 0.5), f('grain', 'Paper grain', 0.3, 0, 1)],
  },
  {
    kind: 'neoFlat',
    label: 'Neo-brutal flat',
    description: 'Turns any picture into neo-brutal graphics: flat loud colours, thick black outlines where colours meet, and a hard offset shadow (no blur) behind everything that isn\u2019t background.',
    params: [e('colours', 'Colours', 'neo', ['neo', 'look']), f('outline', 'Outline', 4, 0, 16, 0.5), f('shadow', 'Shadow offset', 12, 0, 40, 0.5), f('flatten', 'Flatten', 1, 0, 1)],
  },
  {
    kind: 'tvSet',
    label: 'TV set',
    description: 'An old TV screen: curved glass, scanlines, glare and the picture opening out from a line when it switches on. Optionally shows the whole set: a 60s wood console, a 70s portable, an 80s woodgrain set or a 90s black set, with curved glass, scanlines, reflections, light spilling onto the cabinet, and the picture opening out from a line when it switches on.',
    params: [
      e('set', 'Set', 'screen', ['screen', 'console60', 'portable70', 'woodgrain80', 'black90'], 'screen = the picture fills the frame on old curved glass'),
      f('zoom', 'Zoom in', 0.1, 0, 1, 0.01, '0 = whole set · 1 = screen fills the frame'),
      e('fit', 'Widescreen picture', 'crop', ['crop', 'letterbox', 'squash'], 'how a 16:9 look fits the 4:3 tube'),
      f('curve', 'Glass curve', 1, 0, 2),
      f('glare', 'Glare', 1, 0, 2),
      f('room', 'Room light', 1, 0, 2),
      b('powerOn', 'Switch-on effect', true),
    ],
  },
  {
    kind: 'digitalRot',
    label: 'Early digital',
    description: 'Early web video: a small 240-line picture upscaled, macroblocks, 4:2:0 colour, banding, datamosh smears and buffering stalls.',
    params: [
      f('lowres', 'Small video', 0.6, 0, 1),
      f('blocks', 'Macroblocks', 0.5, 0, 1),
      f('bitrate', 'Low bitrate', 0.4, 0, 1),
      f('mosh', 'Datamosh', 0, 0, 1),
      f('buffering', 'Buffering', 0.2, 0, 1),
      i('seed', 'File', 0, 0, 99),
    ],
  },
  {
    kind: 'crt',
    label: 'CRT',
    description: 'Old tube monitor: curved glass, scanlines, an RGB shadow mask and dark corners.',
    params: [f('curvature', 'Curvature', 0.5, 0, 1.5), f('scanlines', 'Scanlines', 0.6, 0, 1), f('mask', 'Shadow mask', 0.4, 0, 1), f('vignette', 'Vignette', 0.5, 0, 1)],
  },
];

const genMap = new Map(GENERATORS.map((g) => [g.kind, g]));
const fxMap = new Map(EFFECTS.map((x) => [x.kind, x]));

export function generatorDef(kind: string): ModuleDef | undefined {
  return genMap.get(kind);
}

export function effectDef(kind: string): ModuleDef | undefined {
  return fxMap.get(kind);
}

export function defaultParams(def: ModuleDef | undefined): ParamBag {
  const out: ParamBag = {};
  for (const p of def?.params ?? []) out[p.key] = p.default;
  return out;
}

export const OPACITY_SPEC: ParamSpec = { key: 'opacity', label: 'Opacity', type: 'float', default: 1, min: 0, max: 1, step: 0.01 };

/** Spec for a layer-relative path ("source.params.x", "fx.2.params.y", "opacity"). */
export function specForLayerPath(layer: { source: { kind: string }; fx: Array<{ type: string }> }, path: string): ParamSpec | undefined {
  if (path === 'opacity') return OPACITY_SPEC;
  const parts = path.split('.');
  if (parts[0] === 'source' && parts[1] === 'params') return generatorDef(layer.source.kind)?.params.find((p) => p.key === parts[2]);
  if (parts[0] === 'fx' && parts[2] === 'params') {
    const fx = layer.fx[Number(parts[1])];
    return fx ? effectDef(fx.type)?.params.find((p) => p.key === parts[3]) : undefined;
  }
  return undefined;
}

export function isNumericSpec(s: ParamSpec | undefined): boolean {
  return !!s && (s.type === 'float' || s.type === 'int');
}

// ---------------------------------------------------------------------------
// Modulation sources (for menus)
// ---------------------------------------------------------------------------

export interface ModSourceOption {
  source: ModSource;
  label: string;
  group: 'Audio' | 'Onset' | 'Tempo' | 'LFO' | 'Envelope' | 'Random';
  /** Extra fields the modulator starts with. */
  init?: Partial<import('@shared/types/engine').Modulator>;
}

export const MOD_SOURCES: ModSourceOption[] = [
  { source: 'audio.sub', label: 'Sub', group: 'Audio' },
  { source: 'audio.bass', label: 'Bass', group: 'Audio' },
  { source: 'audio.lowMid', label: 'Low mid', group: 'Audio' },
  { source: 'audio.mid', label: 'Mid', group: 'Audio' },
  { source: 'audio.highMid', label: 'High mid', group: 'Audio' },
  { source: 'audio.presence', label: 'Presence', group: 'Audio' },
  { source: 'audio.air', label: 'Air', group: 'Audio' },
  { source: 'audio.rms', label: 'RMS level', group: 'Audio' },
  { source: 'audio.energy', label: 'Energy (slow)', group: 'Audio' },
  { source: 'audio.flux', label: 'Flux', group: 'Audio' },
  { source: 'audio.brightness', label: 'Brightness', group: 'Audio' },
  { source: 'audio.onset.kick', label: 'Kick', group: 'Onset' },
  { source: 'audio.onset.snare', label: 'Snare', group: 'Onset' },
  { source: 'audio.onset.hat', label: 'Hat', group: 'Onset' },
  { source: 'audio.onset.any', label: 'Any onset', group: 'Onset' },
  { source: 'tempo.beat', label: 'Beat', group: 'Tempo', init: { shape: 'sine', rate: 1 } },
  { source: 'tempo.bar', label: 'Bar', group: 'Tempo', init: { shape: 'saw', rate: 4 } },
  { source: 'tempo.phrase', label: 'Phrase', group: 'Tempo', init: { shape: 'saw', rate: 16 } },
  { source: 'lfo', label: 'LFO', group: 'LFO', init: { shape: 'sine', hz: 0.25 } },
  { source: 'envelope', label: 'Kick envelope', group: 'Envelope', init: { trigger: 'onset.kick', attackMs: 5, holdMs: 30, decayMs: 250, curve: 'exp' } },
  { source: 'envelope', label: 'Snare envelope', group: 'Envelope', init: { trigger: 'onset.snare', attackMs: 5, holdMs: 20, decayMs: 200, curve: 'exp' } },
  { source: 'envelope', label: 'Drop envelope', group: 'Envelope', init: { trigger: 'drop', attackMs: 30, holdMs: 400, decayMs: 2500, curve: 'smooth' } },
  { source: 'random', label: 'Random per beat', group: 'Random', init: { randomMode: 'hold', rate: 1 } },
  { source: 'random', label: 'Random per bar', group: 'Random', init: { randomMode: 'hold', rate: 4 } },
  { source: 'random', label: 'Smooth noise', group: 'Random', init: { randomMode: 'smooth', hz: 0.3 } },
];

export function modSourceLabel(m: { source: ModSource; trigger?: string; randomMode?: string; rate?: number }): string {
  if (m.source === 'envelope') return `Env · ${m.trigger?.replace('onset.', '') ?? 'kick'}`;
  if (m.source === 'random') return m.randomMode === 'smooth' ? 'Noise' : `Random /${m.rate ?? 1}b`;
  return MOD_SOURCES.find((s) => s.source === m.source)?.label ?? m.source;
}
